[package]
name = "encrypted_fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = { version = "0.14.0", features = ["serializable"] }
clap = { version = "4.5.4", features = ["derive", "cargo"] }
libc = "0.2.153"
env_logger = "0.11.3"
log = "0.4.21"
serde = { version = "1.0.197", features = ["derive"] }
bincode = "1.3.3"
thiserror = "1.0.58"
rand = "0.3"
cryptostream = "0.3.2"
base64 = "=0.13.1"
openssl = "=0.10.64"
aes-stream = "0.2.1"
rust-crypto = "=0.2.36"
ring = "0.17.8"
hex = "0.4.3"
