[package]
name = "encryptedfs"
description = "An encrypted file system that mounts with FUSE on Linux. It can be used to create encrypted directories."
version = "0.1.25"
edition = "2021"
license = "Apache-2.0"
authors = ["Radu Marias <radumarias@gmail.com>"]
repository = "https://github.com/radumarias/encryptedfs"
readme = "README.md"
keywords = ["filesystem", "fuse", "encryption", "system", "security"]
categories = ["cryptography", "filesystem"]
documentation = "https://docs.rs/encryptedfs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo"] }
libc = "0.2.153"
serde = { version = "1.0.197", features = ["derive"] }
bincode = "1.3.3"
thiserror = "1.0.58"
rand = "0.3"
base64 = "=0.13.1"
openssl = "=0.10.64"
fuse3 = { version = "0.7.1", features = ["tokio-runtime", "unprivileged"] }
tokio = { version = "1.36", features = ["macros", "rt-multi-thread", "time", "signal", "process", "rt"] }
futures-util = "0.3.30"
mio = { version = "0.8.11", features = ["os-poll"] }
bytes = "1.5"
tracing = "0.1.40"
tracing-subscriber = "0.3"
ctrlc = { version = "3.1.9" , features = ["termination"]}
parking_lot = "0.12.1"
pbkdf2 = "0.13.0-pre.0"
sha2 = "0.11.0-pre.3"
strum = "0.26.2"
strum_macros = "0.26.2"
rpassword = "7.3.1"
cryptostream = "0.3.2"

[package.metadata.aur]
depends = ["fuse3"]
