name: '#reusable build and tests reusable'
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # TODO: remove this when we cache the builds

jobs:
  tests:
    name: build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          cargo build --workspace --all-targets --all-features
          cargo build --release --workspace --all-targets --all-features
          cargo build --examples --all --all-features
          cargo build --release --examples --all --all-features

      - name: fmt check
        run: cargo fmt --workspace -- --check

      - name: check
        run: cargo check --workspace

      - name: tests
        run: cargo test --release --all --all-features -- nocapture

      - name: tests
        run: cargo publish --dry-run --allow-dirty
