name: clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set default nightly
      run: rustup default nightly && rustup update
    - name: Add clippy
      run: rustup component add clippy
    
    - name: Fmt check
      run: cargo fmt --check

    - name: Check
      run: cargo check --verbose

    - name: Clippy
      run: cargo clippy --all-features --verbose
