name: Docker build
on:
  workflow_call:
    inputs:
      push:
        description: 'If we should also push'
        type: boolean
        required: true
      version:
        description: 'The current value in version file (type: string)'
        type: string
        required: true

jobs:
  docker:
    name: Docker build
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    env:
      # Hostname of your registry
      REGISTRY: docker.io
      REGISTRY_USER: xorio42
      # Image repository, without hostname and tag
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAG: latest
      SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: needs.check_version.outputs.changed == 'true' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build push = ${{ needs.check_version.outputs.changed == 'true'&& github.event_name == 'push' }}"
        uses: docker/build-push-action@v5
        with:
          push: ${{ needs.check_version.outputs.changed == 'true'&& github.event_name == 'push' }}
          tags: ${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          sbom: true
          provenance: true
