name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set default nightly
      run: rustup default nightly && rustup update
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin      
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --tests --lib --verbose -- --show-output --nocapture
    - name: Run doctests
      run: cargo test --package rencfs --doc --verbose -- --show-output --nocapture
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Run tests with coverage
      run: cargo tarpaulin --out Xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
