name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  version:
      uses: radumarias/rencfs/.github/workflows/version_reusable.yml@main
      
  build_and_test:
    name: build and test
    needs: [version]
    uses: radumarias/rencfs/.github/workflows/build_and_tests_reusable.yml@main
    secrets: inherit

  package:
    needs: [version, build_and_test]
    uses: radumarias/rencfs/.github/workflows/package_reusable.yml@main
    with:
      upload_artifacts: false
      version: ${{ needs.version.outputs.version }}
    secrets: inherit
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
